# Generated by Django 3.2.25 on 2024-06-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_groupmember_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='group_name',
            field=models.CharField(default='Test Group', max_length=100),
            preserve_default=False,
        ),
    ]
