# Generated by Django 3.2.25 on 2024-06-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_groupmembership_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembership',
            name='group_name',
        ),
    ]
