# Generated by Django 3.2.25 on 2024-07-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workoutevidence_evidence_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout',
            new_name='GroupWorkout',
        ),
        migrations.RenameModel(
            old_name='WorkoutEvidence',
            new_name='GroupWorkoutEvidence',
        ),
    ]
