# Generated by Django 3.2.25 on 2024-07-06 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='requested_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='Requesting_User', to='core.user'),
            preserve_default=False,
        ),
    ]
