# Generated by Django 3.2.25 on 2024-07-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_friendship_requested_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friendship',
            new_name='Friends',
        ),
    ]
